title: Current Sauce
email: currentsauce1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    I decided to make a website of the things I make and do. A website on electronic projects, hacks, and more by James Kincell.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.currentsauce.co.uk"
twitter_username: currentsauce
github_username:  currentsauce

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme@v1.0.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
paginate: 5
paginate_path: "/blog/page:num"
  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "James K"
      layout: post
      show_sidebar: true

disqus:
    shortname: currentsauce
    
exclude:
  - NonJekyllStuff/
  - PhotosToUse/
  - README.md
  - .gitignore
  - .github/